# Site wide configuration

title:            "@joystick"
locale:           en_US
url:              ""           


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Aristide Fattori
  avatar: avatar.png
  bio: "A mind needs a book like a sword needs a whetstone."
  email: aristidefattori@gmail.com
  twitter: joystick
  gpg: /stuff/0x25578128.gpg
  google:
    plus: AristideFattori
    scholar: QAGMZ9wAAAAJ    
  github: joystick2020
  linkedin: aristidefattori

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "utils"]
